type SkillType = 'JavaScript'
    | 'TypeScript'
    | 'Python'
    | 'Dart'
    | 'C++'
    | 'C#'

    | 'Unity'
    | 'React'
    | 'Flutter'
    | 'Next.js'
    | 'Gatsby'
    | 'Electron'
    | 'HTML'

    | 'Tailwind'
    | 'Chakra UI'
    | 'shadcn/ui'
    | 'CSS'
    | 'Bootstrap'
    
    | 'Jest'
    
    | 'MySQL'
    | 'MongoDB'
    | 'PostgreSQL'
    | 'Prisma'
    
    | 'Docker'
    | 'NPM Package'
    | 'Pusher'
    | 'Open AI'
    | 'AWS S3'
    | 'Uploadthing'